In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('C:/Users/ADMIN/Contacts/Downloads/Folder 1/AirQualityodisha.csv')
df

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0
...,...,...,...,...,...,...,...,...,...,...,...
2387,819,15-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,92,35.0
2388,819,17-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,99,40.0
2389,819,22-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,90,38.0
2390,819,26-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,97,39.0
2391,819,29-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,98,39.0

In [3]:
print(df.head())

   Stn Code Sampling Date   State     City Location of Monitoring Station  \
0        68      02-01-15  Odisha  Talcher        T.T.P.S.Colony, Talcher
1        68      06-01-15  Odisha  Talcher        T.T.P.S.Colony, Talcher
2        68      09-01-15  Odisha  Talcher        T.T.P.S.Colony, Talcher
3        68      13-01-15  Odisha  Talcher        T.T.P.S.Colony, Talcher
4        68      16-01-15  Odisha  Talcher        T.T.P.S.Colony, Talcher

                                 Agency Type of Location  SO2  NO2  RSPM/PM10  \
0  Odisha State Pollution Control Board  Industrial Area   11   24        143
1  Odisha State Pollution Control Board  Industrial Area   10   23        133
2  Odisha State Pollution Control Board  Industrial Area    8   25        125
3  Odisha State Pollution Control Board  Industrial Area   10   25        137
4  Odisha State Pollution Control Board  Industrial Area    9   26        186

   PM 2.5
0   102.0
1    96.0
2   116.0
3   107.0
4   118.0

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Stn Code                        2392 non-null   int64
 1   Sampling Date                   2392 non-null   object
 2   State                           2392 non-null   object
 3   City                            2392 non-null   object
 4   Location of Monitoring Station  2392 non-null   object
 5   Agency                          2392 non-null   object
 6   Type of Location                2392 non-null   object
 7   SO2                             2392 non-null   int64
 8   NO2                             2392 non-null   int64
 9   RSPM/PM10                       2392 non-null   int64
 10  PM 2.5                          2060 non-null   float64
dtypes: float64(1), int64(4), object(6)
memory usage: 205.7+ KB
None

In [5]:
print(df.describe())

          Stn Code          SO2          NO2    RSPM/PM10       PM 2.5
count  2392.000000  2392.000000  2392.000000  2392.000000  2060.000000
mean    486.654264     4.938545    17.698997    88.301003    42.472816
std     220.239379     4.244315     6.705531    39.879856    24.222975
min      68.000000     2.000000     5.000000    15.000000     5.000000
25%     322.000000     2.000000    12.000000    63.000000    28.000000
50%     428.000000     2.000000    16.000000    83.000000    40.000000
75%     694.000000     7.000000    23.000000   105.000000    50.000000
max     819.000000    37.000000    44.000000   590.000000   331.000000

In [6]:
print(df.isnull().sum())

Stn Code                            0
Sampling Date                       0
State                               0
City                                0
Location of Monitoring Station      0
Agency                              0
Type of Location                    0
SO2                                 0
NO2                                 0
RSPM/PM10                           0
PM 2.5                            332
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0
...,...,...,...,...,...,...,...,...,...,...,...
2387,819,15-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,92,35.0
2388,819,17-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,99,40.0
2389,819,22-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,90,38.0
2390,819,26-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,97,39.0
2391,819,29-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,98,39.0

In [12]:
mode=df['PM 2.5'].mode()
mode

0    42.0
Name: PM 2.5, dtype: float64

In [13]:
df = df.fillna(1)

In [14]:
df.isnull().sum()

Stn Code                          0
Sampling Date                     0
State                             0
City                              0
Location of Monitoring Station    0
Agency                            0
Type of Location                  0
SO2                               0
NO2                               0
RSPM/PM10                         0
PM 2.5                            0
dtype: int64

In [15]:
print(df.duplicated().sum())

0

In [16]:
print(df.drop_duplicates())

      Stn Code Sampling Date   State           City  \
0           68      02-01-15  Odisha        Talcher
1           68      06-01-15  Odisha        Talcher
2           68      09-01-15  Odisha        Talcher
3           68      13-01-15  Odisha        Talcher
4           68      16-01-15  Odisha        Talcher
...        ...           ...     ...            ...
2387       819      15-12-15  Odisha  Kalinga Nagar
2388       819      17-12-15  Odisha  Kalinga Nagar
2389       819      22-12-15  Odisha  Kalinga Nagar
2390       819      26-12-15  Odisha  Kalinga Nagar
2391       819      29-12-15  Odisha  Kalinga Nagar

     Location of Monitoring Station                                Agency  \
0           T.T.P.S.Colony, Talcher  Odisha State Pollution Control Board
1           T.T.P.S.Colony, Talcher  Odisha State Pollution Control Board
2           T.T.P.S.Colony, Talcher  Odisha State Pollution Control Board
3           T.T.P.S.Colony, Talcher  Odisha State Pollution Control Board
4           T.T.P.S.Colony, Talcher  Odisha State Pollution Control Board
...                             ...                                   ...
2387     Roof of RO OFFICE BUILDING  Odisha State Pollution Control Board
2388     Roof of RO OFFICE BUILDING  Odisha State Pollution Control Board
2389     Roof of RO OFFICE BUILDING  Odisha State Pollution Control Board
2390     Roof of RO OFFICE BUILDING  Odisha State Pollution Control Board
2391     Roof of RO OFFICE BUILDING  Odisha State Pollution Control Board

     Type of Location  SO2  NO2  RSPM/PM10  PM 2.5
0     Industrial Area   11   24        143   102.0
1     Industrial Area   10   23        133    96.0
2     Industrial Area    8   25        125   116.0
3     Industrial Area   10   25        137   107.0
4     Industrial Area    9   26        186   118.0
...               ...  ...  ...        ...     ...
2387  Industrial Area    2   10         92    35.0
2388  Industrial Area    2   10         99    40.0
2389  Industrial Area    2   10         90    38.0
2390  Industrial Area    2   10         97    39.0
2391  Industrial Area    2   10         98    39.0

[2060 rows x 11 columns]

In [17]:
#data integration
df1=df[['Stn Code','City']].head(10)
df1

   Stn Code     City
0        68  Talcher
1        68  Talcher
2        68  Talcher
3        68  Talcher
4        68  Talcher
5        68  Talcher
6        68  Talcher
7        68  Talcher
8        68  Talcher
9        68  Talcher

In [22]:
df2=df[['Stn Code','SO2']].head(10)
df2

   Stn Code  SO2
0        68   11
1        68   10
2        68    8
3        68   10
4        68    9
5        68   10
6        68   11
7        68   11
8        68   12
9        68    8

In [26]:
mergerd_data=pd.merge(df1,df2,on='Stn Code')
mergerd_data

    Stn Code     City  SO2
0         68  Talcher   11
1         68  Talcher   10
2         68  Talcher    8
3         68  Talcher   10
4         68  Talcher    9
..       ...      ...  ...
95        68  Talcher   10
96        68  Talcher   11
97        68  Talcher   11
98        68  Talcher   12
99        68  Talcher    8

[100 rows x 3 columns]

In [30]:
#Data transformation
#filtering data
filtered_df = df[df['NO2'] <15]
filtered_df

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
157,227,01-01-15,Odisha,Rourkela,"IDL Police Out-post, Sonaparbat, Rourkela",Odisha State Pollution Control Board,"Residential, Rural and other Areas",5,10,71,75.0
158,227,05-01-15,Odisha,Rourkela,"IDL Police Out-post, Sonaparbat, Rourkela",Odisha State Pollution Control Board,"Residential, Rural and other Areas",6,9,75,67.0
159,227,08-01-15,Odisha,Rourkela,"IDL Police Out-post, Sonaparbat, Rourkela",Odisha State Pollution Control Board,"Residential, Rural and other Areas",6,10,72,74.0
160,227,12-01-15,Odisha,Rourkela,"IDL Police Out-post, Sonaparbat, Rourkela",Odisha State Pollution Control Board,"Residential, Rural and other Areas",5,11,70,80.0
161,227,15-01-15,Odisha,Rourkela,"IDL Police Out-post, Sonaparbat, Rourkela",Odisha State Pollution Control Board,"Residential, Rural and other Areas",6,10,81,68.0
...,...,...,...,...,...,...,...,...,...,...,...
2387,819,15-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,92,35.0
2388,819,17-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,99,40.0
2389,819,22-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,90,38.0
2390,819,26-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,97,39.0
2391,819,29-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,98,39.0

In [31]:
#sorting values
sorted_df = df.sort_values(['SO2', 'NO2'])
sorted_df

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
733,370,24-12-15,Odisha,Rourkela,"Regional Office, ORPB, Rourkela",Odisha State Pollution Control Board,"Residential, Rural and other Areas",2,5,36,18.0
1911,695,19-05-15,Odisha,Kalinga Nagar,"Roof of maintenance Office of M/s NINL, Duburi",Odisha State Pollution Control Board,"Residential, Rural and other Areas",2,9,94,38.0
1558,688,22-06-15,Odisha,Bhubaneswar,Chandrasekharpur. Bhubneswar,Odisha State Pollution Control Board,"Residential, Rural and other Areas",2,10,23,9.0
1566,688,23-07-15,Odisha,Bhubaneswar,Chandrasekharpur. Bhubneswar,Odisha State Pollution Control Board,"Residential, Rural and other Areas",2,10,53,14.0
1776,694,02-01-15,Odisha,Kalinga Nagar,Over the Guest House of M/s NINL,Odisha State Pollution Control Board,Industrial Area,2,10,120,53.0
...,...,...,...,...,...,...,...,...,...,...,...
1709,691,23-12-15,Odisha,Paradeep,Over the STP of M/s IFFCO Ltd.,Odisha State Pollution Control Board,Industrial Area,23,13,101,27.0
1710,691,26-12-15,Odisha,Paradeep,Over the STP of M/s IFFCO Ltd.,Odisha State Pollution Control Board,Industrial Area,25,12,141,51.0
1698,691,11-11-15,Odisha,Paradeep,Over the STP of M/s IFFCO Ltd.,Odisha State Pollution Control Board,Industrial Area,26,24,133,42.0
1762,693,11-11-15,Odisha,Paradeep,Near Overhead Water Tank of M/s PPT,Odisha State Pollution Control Board,"Residential, Rural and other Areas",30,28,386,155.0
1730,692,11-11-15,Odisha,Paradeep,Over the Guest House of M/s PPL,Odisha State Pollution Control Board,"Residential, Rural and other Areas",37,24,306,122.0

In [32]:
#Rename
modified_df = df.rename(columns={'Sampling Date': 'Date'})
modified_df

,Stn Code,Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0
...,...,...,...,...,...,...,...,...,...,...,...
2387,819,15-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,92,35.0
2388,819,17-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,99,40.0
2389,819,22-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,90,38.0
2390,819,26-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,97,39.0
2391,819,29-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,98,39.0

In [33]:
#grouping
grouped_df = df.groupby('City')['SO2'].mean()
grouped_df

City
Angul            10.519048
Balasore          3.540000
Berhampur         2.000000
Bhubaneswar       2.213178
Cuttack           2.765343
Kalinga Nagar     2.009804
Keonjhar          2.000000
Konark            2.046154
Paradeep         14.869048
Puri              2.485714
Rayagada          4.132184
Rourkela          8.692568
Sambalpur         4.131579
Talcher           9.990385
Name: SO2, dtype: float64

In [42]:
modified_df['NO2'] = np.square(df['NO2'])
modified_df

,Stn Code,Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,576,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,529,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,625,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,625,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,676,186,118.0
...,...,...,...,...,...,...,...,...,...,...,...
2387,819,15-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,100,92,35.0
2388,819,17-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,100,99,40.0
2389,819,22-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,100,90,38.0
2390,819,26-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,100,97,39.0
2391,819,29-12-15,Odisha,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,100,98,39.0

In [45]:
#error corecting
try:
    print(df['NO2'])
except ValueError as e:
    print("KeyError:", e)

0       24
1       23
2       25
3       25
4       26
        ..
2387    10
2388    10
2389    10
2390    10
2391    10
Name: NO2, Length: 2060, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X = df[['RSPM/PM10','NO2']]  # Features (input variables)
y = df['PM 2.5']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # Split data into training and testing sets

In [63]:
lm=LinearRegression(fit_intercept=False)
lm

LinearRegression(fit_intercept=False)

In [64]:
lm.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [65]:
lm.coef_

array([0.42946317, 0.23589224])

In [68]:
lm.predict([[100,2]])

E:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([43.41810117])